# Generated by Django 4.1.5 on 2023-01-27 12:57

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=100)),
                ("user", models.CharField(db_index=True, max_length=100)),
                ("post_content", tinymce.models.HTMLField()),
                ("inital_post_date", models.DateTimeField()),
                ("last_modified_post_date", models.DateTimeField()),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(db_index=True, max_length=100)),
                ("post_content", tinymce.models.HTMLField()),
                ("inital_post_date", models.DateTimeField()),
                ("votes", models.IntegerField(default=0)),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="my_forum.posts",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Comments",
            },
        ),
    ]
