# Generated by Django 4.1.5 on 2023-03-13 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_forum", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="inital_post_date",
            new_name="initial_post_date",
        ),
        migrations.RenameField(
            model_name="posts",
            old_name="inital_post_date",
            new_name="initial_post_date",
        ),
    ]
